### ISSUE TITLE
Why I can't open files in split windows, tabs, as I can in CtrlP?

### ISSUE THREAD

**Issue by yevhen-m** [kshenoy/vim-ctrlp-args#1]

**Comment by kshenoy** [comment]
Hey sorry for the delay. I was busy with work and this being my first CtrlP extension, I had to do a lot of digging to understand how CtrlP works. Thank you for your patience. Can you give it a try now?

**Comment by yevhen-m** [comment]
Thanks for your help, but I no longer use CtrlP plugin and its extensions.

**Comment by kshenoy** [comment]
No worries. Out of curiosity, what did you switch to?

**Comment by yevhen-m** [comment]
Fzf-vim, it's far way better.
